export interface CollegeProfile {
  id: string;
  name: string;
  shortName: string;
  stream: "Science & Tech" | "Commerce & Business" | "Arts & Humanities" | "Law" | "Design & Media" | "Medical & Bio";
  city: string;
  state: string;
  type: "IIT" | "NIT / IIIT" | "Central University" | "Top Private" | "State Govt" | "National Institute" | "Medical AIIMS/Govt" | "NLU / Law";
  nirfRank: number | string;
  annualFeesEstimate: string;
  medianCtcEstimate: string;
  admissionExam: string;
  rating: number;
  highlight: string;
  popularPrograms: string[];
  keyStrengths: string[];
  specializations?: string[];
}

export const COLLEGE_DIRECTORY: CollegeProfile[] = [
  // =========================================================================
  // 1. SCIENCE & TECH: PREMIER IITs
  // =========================================================================
  {
    id: "iit-madras",
    name: "Indian Institute of Technology Madras",
    shortName: "IIT Madras",
    stream: "Science & Tech",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "IIT",
    nirfRank: 1,
    annualFeesEstimate: "₹2.2 Lakhs / yr",
    medianCtcEstimate: "₹21.5 LPA",
    admissionExam: "JEE Advanced / Direct Qualifier",
    rating: 5.0,
    highlight: "Ranked #1 Engineering Institute in India by NIRF. Pioneers in B.Tech in AI & Data Analytics and BS in Data Science.",
    popularPrograms: ["B.Tech AI & Data Analytics", "B.Tech Computer Science", "BS in Data Science"],
    keyStrengths: ["Ranked #1 in NIRF Overall for 5 years", "Robert Bosch Centre for Data Science & AI", "IITM Research Park ecosystem"],
    specializations: ["AI", "Data Science", "Machine Learning", "Robotics", "Computer Science"],
  },
  {
    id: "iit-delhi",
    name: "Indian Institute of Technology Delhi",
    shortName: "IIT Delhi",
    stream: "Science & Tech",
    city: "New Delhi",
    state: "Delhi",
    type: "IIT",
    nirfRank: 2,
    annualFeesEstimate: "₹2.4 Lakhs / yr",
    medianCtcEstimate: "₹20.5 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.9,
    highlight: "Capital city tech powerhouse with Yardi School of AI and highest domestic tech placement packages.",
    popularPrograms: ["B.Tech Computer Science", "M.Tech Artificial Intelligence", "B.Tech Mathematics & Computing"],
    keyStrengths: ["Yardi School of Artificial Intelligence", "Top tech consulting recruitment", "Central research facilities"],
    specializations: ["AI", "Data Science", "Cybersecurity", "Fintech", "Cloud Computing"],
  },
  {
    id: "iit-bombay",
    name: "Indian Institute of Technology Bombay",
    shortName: "IIT Bombay",
    stream: "Science & Tech",
    city: "Mumbai",
    state: "Maharashtra",
    type: "IIT",
    nirfRank: 3,
    annualFeesEstimate: "₹2.5 Lakhs / yr",
    medianCtcEstimate: "₹21.8 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.9,
    highlight: "India's premier engineering destination with world-class entrepreneurship and tech ecosystem.",
    popularPrograms: ["B.Tech Computer Science", "Electrical Engineering", "BS Mathematics & Computing"],
    keyStrengths: ["Top Silicon Valley & Mumbai placements", "E-Cell startup hub", "Global faculty network"],
    specializations: ["AI", "Data Science", "Machine Learning", "Computer Science", "Fintech"],
  },
  {
    id: "iit-kanpur",
    name: "Indian Institute of Technology Kanpur",
    shortName: "IIT Kanpur",
    stream: "Science & Tech",
    city: "Kanpur",
    state: "Uttar Pradesh",
    type: "IIT",
    nirfRank: 4,
    annualFeesEstimate: "₹2.3 Lakhs / yr",
    medianCtcEstimate: "₹19.5 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.9,
    highlight: "World-renowned theoretical computer science, C3iHub for cybersecurity, and cognitive science research.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Cyber Security", "B.Tech Aerospace Engineering"],
    keyStrengths: ["C3iHub National Cybersecurity Hub", "High algorithmic research output", "Flight laboratory with airstrip"],
    specializations: ["Cybersecurity", "AI", "Data Science", "Aerospace", "Theoretical CS"],
  },
  {
    id: "iit-kharagpur",
    name: "Indian Institute of Technology Kharagpur",
    shortName: "IIT Kharagpur",
    stream: "Science & Tech",
    city: "Kharagpur",
    state: "West Bengal",
    type: "IIT",
    nirfRank: 5,
    annualFeesEstimate: "₹2.2 Lakhs / yr",
    medianCtcEstimate: "₹18.8 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.8,
    highlight: "First IIT established in India; largest campus with Centre of Excellence in AI and multidisciplinary courses.",
    popularPrograms: ["B.Tech Computer Science", "Dual Degree AI & ML", "B.Tech Electronics"],
    keyStrengths: ["Centre of Excellence in Artificial Intelligence", "2,100-acre self-contained campus", "Huge global alumni network"],
    specializations: ["AI", "Machine Learning", "Robotics", "Data Science", "Embedded Systems"],
  },
  {
    id: "iit-roorkee",
    name: "Indian Institute of Technology Roorkee",
    shortName: "IIT Roorkee",
    stream: "Science & Tech",
    city: "Roorkee",
    state: "Uttarakhand",
    type: "IIT",
    nirfRank: 6,
    annualFeesEstimate: "₹2.2 Lakhs / yr",
    medianCtcEstimate: "₹18.0 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.8,
    highlight: "Oldest technical institution in Asia; Mehta Family School of Data Science and AI.",
    popularPrograms: ["B.Tech Data Science & AI", "B.Tech Computer Science", "B.Tech Electronics"],
    keyStrengths: ["Mehta Family School of Data Science and AI", "175+ years heritage", "Strong hydrology and tech labs"],
    specializations: ["Data Science", "AI", "Cloud Computing", "Computer Science"],
  },
  {
    id: "iit-guwahati",
    name: "Indian Institute of Technology Guwahati",
    shortName: "IIT Guwahati",
    stream: "Science & Tech",
    city: "Guwahati",
    state: "Assam",
    type: "IIT",
    nirfRank: 7,
    annualFeesEstimate: "₹2.2 Lakhs / yr",
    medianCtcEstimate: "₹17.5 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.8,
    highlight: "Mehta Family School of Data Science & AI, world-class design department, and scenic campus.",
    popularPrograms: ["B.Tech Data Science & AI", "B.Des (Design)", "B.Tech Computer Science"],
    keyStrengths: ["Pioneering B.Tech in Data Science & AI", "Param-Kamrupa Supercomputing facility", "Top tier design school"],
    specializations: ["Data Science", "AI", "UX Design", "Machine Learning"],
  },
  {
    id: "iit-hyderabad",
    name: "Indian Institute of Technology Hyderabad",
    shortName: "IIT Hyderabad",
    stream: "Science & Tech",
    city: "Sangareddy",
    state: "Telangana",
    type: "IIT",
    nirfRank: 8,
    annualFeesEstimate: "₹2.3 Lakhs / yr",
    medianCtcEstimate: "₹20.0 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.9,
    highlight: "First institute in India to offer B.Tech in Artificial Intelligence; futuristic fractal academic curriculum.",
    popularPrograms: ["B.Tech Artificial Intelligence", "B.Tech Computational Engineering", "B.Tech Computer Science"],
    keyStrengths: ["First B.Tech AI program in India", "Japanese collaboration & TiHAN autonomous tech", "Rapid NIRF rise"],
    specializations: ["AI", "Autonomous Systems", "Data Science", "Deep Learning", "Robotics"],
  },
  {
    id: "iit-bhu",
    name: "Indian Institute of Technology (BHU) Varanasi",
    shortName: "IIT (BHU)",
    stream: "Science & Tech",
    city: "Varanasi",
    state: "Uttar Pradesh",
    type: "IIT",
    nirfRank: 10,
    annualFeesEstimate: "₹2.1 Lakhs / yr",
    medianCtcEstimate: "₹17.2 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.7,
    highlight: "Historic tech institution within the sprawling Banaras Hindu University campus with strong core coding culture.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Electronics", "Integrated M.Tech Math & Computing"],
    keyStrengths: ["High-density placement offers", "Strong competitive programming culture", "Rich heritage"],
    specializations: ["Computer Science", "Algorithms", "Fintech", "Data Analytics"],
  },

  // =========================================================================
  // 2. SCIENCE & TECH: TOP NITs & IIITs
  // =========================================================================
  {
    id: "iiit-hyderabad",
    name: "International Institute of Information Technology Hyderabad",
    shortName: "IIIT Hyderabad",
    stream: "Science & Tech",
    city: "Hyderabad",
    state: "Telangana",
    type: "NIT / IIIT",
    nirfRank: 55,
    annualFeesEstimate: "₹4.0 Lakhs / yr",
    medianCtcEstimate: "₹30.5 LPA",
    admissionExam: "JEE Main / UGEE",
    rating: 5.0,
    highlight: "Unmatched research culture in Computer Vision, NLP, and Robotics; highest median CS placements in India.",
    popularPrograms: ["B.Tech Computer Science", "Dual Degree CSE + Research in AI", "B.Tech ECE"],
    keyStrengths: ["Highest CS median salary in India (>₹30 LPA)", "Kohli Centre on Intelligent Systems", "Top ACL/CVPR publications"],
    specializations: ["AI", "Computer Vision", "NLP", "Machine Learning", "Robotics", "Data Science"],
  },
  {
    id: "iiit-delhi",
    name: "Indraprastha Institute of Information Technology Delhi",
    shortName: "IIIT Delhi",
    stream: "Science & Tech",
    city: "New Delhi",
    state: "Delhi",
    type: "NIT / IIIT",
    nirfRank: 75,
    annualFeesEstimate: "₹4.5 Lakhs / yr",
    medianCtcEstimate: "₹18.5 LPA",
    admissionExam: "JEE Main (JAC Delhi)",
    rating: 4.8,
    highlight: "State-of-the-art specialized degrees in CS & AI, CS & Biosciences, and CS & Social Sciences.",
    popularPrograms: ["B.Tech Computer Science & AI (CSAI)", "B.Tech CS & Applied Mathematics", "B.Tech CS & Design"],
    keyStrengths: ["Dedicated CSAI department", "Infosys Centre for AI", "Modern high-tech Delhi campus"],
    specializations: ["AI", "Data Science", "Machine Learning", "Cybersecurity", "HCI & Design"],
  },
  {
    id: "iiit-bangalore",
    name: "International Institute of Information Technology Bangalore",
    shortName: "IIIT Bangalore",
    stream: "Science & Tech",
    city: "Bengaluru",
    state: "Karnataka",
    type: "NIT / IIIT",
    nirfRank: 74,
    annualFeesEstimate: "₹4.6 Lakhs / yr",
    medianCtcEstimate: "₹24.0 LPA",
    admissionExam: "JEE Main",
    rating: 4.8,
    highlight: "Located in the heart of Electronics City Bangalore with direct industry integration and high-paying tech placements.",
    popularPrograms: ["Integrated M.Tech Computer Science", "Integrated M.Tech ECE", "M.Tech Data Science"],
    keyStrengths: ["Electronics City tech park location", "Exceptional product company hiring", "Deep AI & Data Science focus"],
    specializations: ["AI", "Data Science", "Cloud Systems", "VLSI", "Software Engineering"],
  },
  {
    id: "iiit-allahabad",
    name: "Indian Institute of Information Technology Allahabad",
    shortName: "IIIT Allahabad",
    stream: "Science & Tech",
    city: "Prayagraj",
    state: "Uttar Pradesh",
    type: "NIT / IIIT",
    nirfRank: 89,
    annualFeesEstimate: "₹2.0 Lakhs / yr",
    medianCtcEstimate: "₹20.5 LPA",
    admissionExam: "JEE Main (JoSAA / CSAB)",
    rating: 4.8,
    highlight: "Renowned coding powerhouse with one of the highest median packages among central technical institutes.",
    popularPrograms: ["B.Tech Information Technology", "B.Tech IT (Business Informatics)", "B.Tech ECE"],
    keyStrengths: ["Consistently top Google Summer of Code selections", "Top tier median salaries", "Strong CP culture"],
    specializations: ["Software Engineering", "Data Science", "Cybersecurity", "Fintech"],
  },
  {
    id: "nit-trichy",
    name: "National Institute of Technology Tiruchirappalli",
    shortName: "NIT Trichy",
    stream: "Science & Tech",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "NIT / IIIT",
    nirfRank: 9,
    annualFeesEstimate: "₹1.8 Lakhs / yr",
    medianCtcEstimate: "₹15.8 LPA",
    admissionExam: "JEE Main (JoSAA)",
    rating: 4.8,
    highlight: "Ranked #1 NIT in India. Exceptional ROI with heavily subsidized government fee and elite placements.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Electronics & Communication", "B.Tech Mechanical"],
    keyStrengths: ["Consistently #1 NIT across India", "Top tier campus recruitment", "Affordable fee structure"],
    specializations: ["Computer Science", "Data Science", "AI", "VLSI", "Robotics"],
  },
  {
    id: "nit-surathkal",
    name: "National Institute of Technology Karnataka Surathkal",
    shortName: "NIT Surathkal",
    stream: "Science & Tech",
    city: "Mangaluru",
    state: "Karnataka",
    type: "NIT / IIIT",
    nirfRank: 12,
    annualFeesEstimate: "₹1.8 Lakhs / yr",
    medianCtcEstimate: "₹16.0 LPA",
    admissionExam: "JEE Main (JoSAA)",
    rating: 4.8,
    highlight: "Private beach campus with cutting-edge B.Tech in Artificial Intelligence and Information Technology.",
    popularPrograms: ["B.Tech Artificial Intelligence", "B.Tech Information Technology", "B.Tech Computer Science"],
    keyStrengths: ["Dedicated B.Tech in AI", "Coastline campus with private beach", "High product firm placements"],
    specializations: ["AI", "Data Science", "Machine Learning", "Cloud Computing"],
  },
  {
    id: "nit-rourkela",
    name: "National Institute of Technology Rourkela",
    shortName: "NIT Rourkela",
    stream: "Science & Tech",
    city: "Rourkela",
    state: "Odisha",
    type: "NIT / IIIT",
    nirfRank: 16,
    annualFeesEstimate: "₹1.8 Lakhs / yr",
    medianCtcEstimate: "₹13.5 LPA",
    admissionExam: "JEE Main (JoSAA)",
    rating: 4.7,
    highlight: "Expansive campus with strong multidisciplinary research and top manufacturing and software recruitment.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Electronics", "B.Tech Industrial Design"],
    keyStrengths: ["Low tuition fee with high ROI", "Massive campus infrastructure", "Strong student clubs"],
    specializations: ["Computer Science", "Data Analytics", "AI", "Industrial Design"],
  },
  {
    id: "nit-warangal",
    name: "National Institute of Technology Warangal",
    shortName: "NIT Warangal",
    stream: "Science & Tech",
    city: "Warangal",
    state: "Telangana",
    type: "NIT / IIIT",
    nirfRank: 21,
    annualFeesEstimate: "₹1.8 Lakhs / yr",
    medianCtcEstimate: "₹15.0 LPA",
    admissionExam: "JEE Main (JoSAA)",
    rating: 4.7,
    highlight: "Historic first RECs in India; top computer science cutoffs with exceptional software engineering hiring.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Mathematics & Computing", "B.Tech ECE"],
    keyStrengths: ["High coding benchmark", "Superb alumni network across Hyderabad and Bengaluru", "Subsidized fees"],
    specializations: ["Data Science", "AI", "Algorithms", "Cybersecurity"],
  },
  {
    id: "nit-calicut",
    name: "National Institute of Technology Calicut",
    shortName: "NIT Calicut",
    stream: "Science & Tech",
    city: "Kozhikode",
    state: "Kerala",
    type: "NIT / IIIT",
    nirfRank: 23,
    annualFeesEstimate: "₹1.8 Lakhs / yr",
    medianCtcEstimate: "₹13.8 LPA",
    admissionExam: "JEE Main (JoSAA)",
    rating: 4.6,
    highlight: "South India tech destination with strong computing and electronics faculties.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Electronics", "B.Tech Electrical"],
    keyStrengths: ["Excellent faculty to student ratio", "High placement percentage in CS/EC", "Scenic foothills campus"],
    specializations: ["Computer Science", "AI", "Signal Processing"],
  },

  // =========================================================================
  // 3. SCIENCE & TECH: PREMIER STATE UNIVERSITIES & BITS
  // =========================================================================
  {
    id: "bits-pilani",
    name: "Birla Institute of Technology and Science Pilani",
    shortName: "BITS Pilani",
    stream: "Science & Tech",
    city: "Pilani",
    state: "Rajasthan",
    type: "Top Private",
    nirfRank: 20,
    annualFeesEstimate: "₹5.5 Lakhs / yr",
    medianCtcEstimate: "₹18.5 LPA",
    admissionExam: "BITSAT",
    rating: 4.9,
    highlight: "India's premier private tech university. Zero attendance rule, Practice School industry semesters, and unicorn founders.",
    popularPrograms: ["B.E. Computer Science", "M.Sc Economics + B.E. CS Dual", "B.E. Electronics"],
    keyStrengths: ["Top 3 startup founder alma mater in India", "Practice School 6-month industry internships", "Merit-based admission via BITSAT"],
    specializations: ["AI", "Data Science", "Fintech", "Software Engineering", "Product Management"],
  },
  {
    id: "bits-goa",
    name: "BITS Pilani - K.K. Birla Goa Campus",
    shortName: "BITS Goa",
    stream: "Science & Tech",
    city: "Zuarinagar",
    state: "Goa",
    type: "Top Private",
    nirfRank: 20,
    annualFeesEstimate: "₹5.5 Lakhs / yr",
    medianCtcEstimate: "₹18.0 LPA",
    admissionExam: "BITSAT",
    rating: 4.8,
    highlight: "High-tech coastal campus with exact same centralized BITS placement pool and top US tech recruitment.",
    popularPrograms: ["B.E. Computer Science", "B.E. Electronics & Instrumentation", "M.Sc Mathematics + CS Dual"],
    keyStrengths: ["Common centralized placement across all BITS campuses", "Vibrant tech fest Waves & Quark", "Zero mandatory attendance"],
    specializations: ["AI", "Machine Learning", "Data Science", "Cybersecurity"],
  },
  {
    id: "dtu-delhi",
    name: "Delhi Technological University",
    shortName: "DTU Delhi",
    stream: "Science & Tech",
    city: "New Delhi",
    state: "Delhi",
    type: "State Govt",
    nirfRank: 29,
    annualFeesEstimate: "₹2.1 Lakhs / yr",
    medianCtcEstimate: "₹15.2 LPA",
    admissionExam: "JEE Main (JAC Delhi)",
    rating: 4.7,
    highlight: "Formerly DCE (Delhi College of Engineering); top ROI with massive tech hiring footprint across NCR.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Information Technology", "B.Tech Software Engineering"],
    keyStrengths: ["Superb ROI (Govt fee vs >15LPA average)", "Unrivaled alumni network in tech", "Hub of competitive programming"],
    specializations: ["Data Science", "AI", "Software Engineering", "Automotive Tech"],
  },
  {
    id: "nsut-delhi",
    name: "Netaji Subhas University of Technology",
    shortName: "NSUT Delhi",
    stream: "Science & Tech",
    city: "New Delhi",
    state: "Delhi",
    type: "State Govt",
    nirfRank: 60,
    annualFeesEstimate: "₹2.2 Lakhs / yr",
    medianCtcEstimate: "₹15.0 LPA",
    admissionExam: "JEE Main (JAC Delhi)",
    rating: 4.6,
    highlight: "Formerly NSIT; premier engineering destination in Dwarka, Delhi with dedicated Artificial Intelligence & Data Science branches.",
    popularPrograms: ["B.Tech CS with AI (CSAI)", "B.Tech Mathematics & Computing", "B.Tech Information Technology"],
    keyStrengths: ["Dedicated CSAI stream", "Tier-1 tech company recruitment (Google, Microsoft, Uber)", "State subsidized fees"],
    specializations: ["AI", "Data Science", "Machine Learning", "Fintech"],
  },
  {
    id: "jadavpur-university",
    name: "Jadavpur University - Faculty of Engineering",
    shortName: "Jadavpur University",
    stream: "Science & Tech",
    city: "Kolkata",
    state: "West Bengal",
    type: "State Govt",
    nirfRank: 10,
    annualFeesEstimate: "₹0.10 Lakhs / yr",
    medianCtcEstimate: "₹14.8 LPA",
    admissionExam: "WBJEE",
    rating: 4.9,
    highlight: "Highest ROI in Asia: 4-year degree fee is under ₹10,000 total with median CTC exceeding ₹14 LPA.",
    popularPrograms: ["B.E. Computer Science", "B.E. Electronics & Telecommunication", "B.E. Information Technology"],
    keyStrengths: ["Practically free higher education (~₹2,400/yr)", "Top 10 NIRF ranking", "Elite research output"],
    specializations: ["Computer Science", "Algorithms", "AI", "Data Science"],
  },
  {
    id: "coep-pune",
    name: "COEP Technological University",
    shortName: "COEP Pune",
    stream: "Science & Tech",
    city: "Pune",
    state: "Maharashtra",
    type: "State Govt",
    nirfRank: 73,
    annualFeesEstimate: "₹1.1 Lakhs / yr",
    medianCtcEstimate: "₹11.5 LPA",
    admissionExam: "MHT-CET / JEE Main",
    rating: 4.7,
    highlight: "Established in 1854; one of the oldest and most prestigious state technical universities in India.",
    popularPrograms: ["B.Tech Computer Engineering", "B.Tech Artificial Intelligence", "B.Tech Mechanical"],
    keyStrengths: ["Pioneering heritage with Sir M. Visvesvaraya", "Prime Pune tech corridor location", "Affordable state fees"],
    specializations: ["AI", "Robotics", "Data Science", "Automotive"],
  },

  // =========================================================================
  // 4. SCIENCE & TECH: TOP PRIVATE INSTITUTES
  // =========================================================================
  {
    id: "vit-vellore",
    name: "Vellore Institute of Technology",
    shortName: "VIT Vellore",
    stream: "Science & Tech",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "Top Private",
    nirfRank: 11,
    annualFeesEstimate: "₹2.0 - 4.5 Lakhs / yr",
    medianCtcEstimate: "₹9.2 LPA",
    admissionExam: "VITEEE",
    rating: 4.5,
    highlight: "Ranked #11 in NIRF Engineering. Offers specialized B.Tech programs in AI & ML, Data Science, and Information Security.",
    popularPrograms: ["B.Tech CSE with spec in Data Science", "B.Tech CSE with spec in AI & ML", "B.Tech CSE Information Security"],
    keyStrengths: ["Massive campus placements (>900 recruiting companies)", "ABET accredited programs", "Flexible credit system (FFCS)"],
    specializations: ["AI", "Data Science", "Cybersecurity", "Cloud Computing", "IoT", "Gaming"],
  },
  {
    id: "rvce-bangalore",
    name: "RV College of Engineering",
    shortName: "RVCE Bangalore",
    stream: "Science & Tech",
    city: "Bengaluru",
    state: "Karnataka",
    type: "Top Private",
    nirfRank: 96,
    annualFeesEstimate: "₹3.0 - 9.0 Lakhs / yr",
    medianCtcEstimate: "₹14.5 LPA",
    admissionExam: "KCET / COMEDK / Management",
    rating: 4.7,
    highlight: "Bengaluru's top private engineering institution with Silicon Valley of India startup and tech recruitment connections.",
    popularPrograms: ["B.E. Computer Science", "B.E. Artificial Intelligence & Machine Learning", "B.E. Information Science"],
    keyStrengths: ["Located in Bengaluru tech epicenter", "Tier-1 software packages", "Strong core engineering"],
    specializations: ["AI", "Machine Learning", "Data Science", "Cloud Systems", "Embedded Systems"],
  },
  {
    id: "manipal-mit",
    name: "Manipal Institute of Technology (MAHE)",
    shortName: "MIT Manipal",
    stream: "Science & Tech",
    city: "Manipal",
    state: "Karnataka",
    type: "Top Private",
    nirfRank: 61,
    annualFeesEstimate: "₹4.5 Lakhs / yr",
    medianCtcEstimate: "₹11.2 LPA",
    admissionExam: "MET (Manipal Entrance Test)",
    rating: 4.6,
    highlight: "Alma mater of Satya Nadella (Microsoft CEO); renowned university town with cutting-edge computing labs.",
    popularPrograms: ["B.Tech Computer Science", "B.Tech Data Science & Engineering", "B.Tech Cyber Physical Systems"],
    keyStrengths: ["Global alumni network", "Cosmopolitan student body", "Dedicated Data Science department"],
    specializations: ["Data Science", "AI", "Cybersecurity", "Fintech"],
  },
  {
    id: "thapar-patiala",
    name: "Thapar Institute of Engineering and Technology",
    shortName: "Thapar Patiala",
    stream: "Science & Tech",
    city: "Patiala",
    state: "Punjab",
    type: "Top Private",
    nirfRank: 22,
    annualFeesEstimate: "₹4.2 Lakhs / yr",
    medianCtcEstimate: "₹12.0 LPA",
    admissionExam: "JEE Main / Class 12 Merit",
    rating: 4.6,
    highlight: "Academic collaboration with Trinity College Dublin; top tier engineering placements across North India.",
    popularPrograms: ["B.E. Computer Engineering", "B.E. Computer Science & Business Systems", "B.E. Data Science"],
    keyStrengths: ["Trinity College Dublin international credit transfer", "Vast campus with modern labs", "Tier-1 recruiter presence"],
    specializations: ["Computer Science", "Data Science", "AI", "Business Analytics"],
  },
  {
    id: "srm-ktr",
    name: "SRM Institute of Science and Technology",
    shortName: "SRM Kattankulathur",
    stream: "Science & Tech",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "Top Private",
    nirfRank: 28,
    annualFeesEstimate: "₹3.5 - 4.5 Lakhs / yr",
    medianCtcEstimate: "₹8.5 LPA",
    admissionExam: "SRMJEEE",
    rating: 4.4,
    highlight: "Mega campus in Chennai with specialized programs in Big Data, Cloud, AI, and Cybersecurity.",
    popularPrograms: ["B.Tech CSE with AI & ML", "B.Tech CSE with Big Data Analytics", "B.Tech CSE with Cloud Computing"],
    keyStrengths: ["Vast industry tie-ups", "Semester Abroad Program (SAP)", "Extensive specialization choices"],
    specializations: ["AI", "Data Science", "Cloud Computing", "Cybersecurity", "Blockchain"],
  },
  {
    id: "plaksha-university",
    name: "Plaksha University",
    shortName: "Plaksha Mohali",
    stream: "Science & Tech",
    city: "Mohali",
    state: "Punjab",
    type: "Top Private",
    nirfRank: "Emerging Tech",
    annualFeesEstimate: "₹8.0 Lakhs / yr",
    medianCtcEstimate: "₹17.5 LPA",
    admissionExam: "SAT / JEE Main / Plaksha Test",
    rating: 4.8,
    highlight: "Reimagined technology university backed by 100+ tech leaders with interdisciplinary degrees in Robotics and AI.",
    popularPrograms: ["B.Tech Computer Science & AI", "B.Tech Robotics & Cyber-Physical Systems", "B.Tech Data Science, Economics & Business"],
    keyStrengths: ["Founded by global tech CEOs", "Project-based experiential curriculum", "Silicon Valley faculty advisors"],
    specializations: ["AI", "Data Science", "Robotics", "Deep Tech", "Fintech"],
  },

  // =========================================================================
  // 5. MEDICAL & BIO / HEALTHCARE
  // =========================================================================
  {
    id: "aiims-delhi",
    name: "All India Institute of Medical Sciences New Delhi",
    shortName: "AIIMS New Delhi",
    stream: "Medical & Bio",
    city: "New Delhi",
    state: "Delhi",
    type: "Medical AIIMS/Govt",
    nirfRank: 1,
    annualFeesEstimate: "₹0.02 Lakhs / yr",
    medianCtcEstimate: "₹18.0 LPA",
    admissionExam: "NEET UG",
    rating: 5.0,
    highlight: "The pinnacle of medical education in South Asia. Practically free tuition, massive clinical exposure, and world-class research.",
    popularPrograms: ["MBBS", "B.Sc (Hons) Nursing", "MD / MS Specializations"],
    keyStrengths: ["Ranked #1 Medical College in India consistently", "Subsidized government fee (under ₹6,000 for entire MBBS)", "Pioneering clinical research"],
    specializations: ["Surgery", "Internal Medicine", "Cardiology", "Neuroscience", "Pediatrics"],
  },
  {
    id: "cmc-vellore",
    name: "Christian Medical College Vellore",
    shortName: "CMC Vellore",
    stream: "Medical & Bio",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "Top Private",
    nirfRank: 3,
    annualFeesEstimate: "₹0.50 Lakhs / yr",
    medianCtcEstimate: "₹14.0 LPA",
    admissionExam: "NEET UG",
    rating: 4.9,
    highlight: "Legendary patient care and community health training; ranked #3 in India with highly subsidized fee structure.",
    popularPrograms: ["MBBS", "B.Sc Nursing", "Allied Health Sciences"],
    keyStrengths: ["Ranked #3 in NIRF Medical", "Focus on ethical and compassionate patient care", "Top community health network"],
    specializations: ["Community Medicine", "Surgery", "Oncology", "Hematology"],
  },
  {
    id: "jipmer-puducherry",
    name: "Jawaharlal Institute of Postgraduate Medical Education and Research",
    shortName: "JIPMER",
    stream: "Medical & Bio",
    city: "Puducherry",
    state: "Puducherry",
    type: "Medical AIIMS/Govt",
    nirfRank: 5,
    annualFeesEstimate: "₹0.15 Lakhs / yr",
    medianCtcEstimate: "₹15.0 LPA",
    admissionExam: "NEET UG",
    rating: 4.9,
    highlight: "Institute of National Importance with autonomous status; premier clinical training and subsidized residency.",
    popularPrograms: ["MBBS", "B.Sc Allied Medical Sciences", "MD / MS"],
    keyStrengths: ["Institute of National Importance", "High volume multi-specialty hospital", "Extremely low fee with high stipend"],
    specializations: ["General Medicine", "Pediatrics", "Emergency Care", "Anesthesiology"],
  },
  {
    id: "aiims-bhubaneswar",
    name: "All India Institute of Medical Sciences Bhubaneswar",
    shortName: "AIIMS Bhubaneswar",
    stream: "Medical & Bio",
    city: "Bhubaneswar",
    state: "Odisha",
    type: "Medical AIIMS/Govt",
    nirfRank: 17,
    annualFeesEstimate: "₹0.02 Lakhs / yr",
    medianCtcEstimate: "₹14.5 LPA",
    admissionExam: "NEET UG",
    rating: 4.8,
    highlight: "Fastest-growing new AIIMS with state-of-the-art super-specialty hospital and modern medical simulation labs.",
    popularPrograms: ["MBBS", "B.Sc Nursing", "MD / MS"],
    keyStrengths: ["Top tier clinical infrastructure in Eastern India", "Central government funding", "Zero tuition burden"],
    specializations: ["Cardiology", "Neurology", "Gastroenterology", "Surgical Oncology"],
  },
  {
    id: "mamc-delhi",
    name: "Maulana Azad Medical College",
    shortName: "MAMC Delhi",
    stream: "Medical & Bio",
    city: "New Delhi",
    state: "Delhi",
    type: "State Govt",
    nirfRank: 24,
    annualFeesEstimate: "₹0.05 Lakhs / yr",
    medianCtcEstimate: "₹16.0 LPA",
    admissionExam: "NEET UG",
    rating: 4.9,
    highlight: "Affiliated with Lok Nayak Hospital; handles millions of OPD cases annually, giving unparalleled clinical exposure.",
    popularPrograms: ["MBBS", "MD Internal Medicine", "MS General Surgery"],
    keyStrengths: ["Associated with 2,800+ bed Lok Nayak Hospital", "Top 50 NEET UG cutoff ranks", "Top residency match in USA & UK"],
    specializations: ["Internal Medicine", "Surgery", "Pediatrics", "Radiology"],
  },
  {
    id: "kasturba-manipal",
    name: "Kasturba Medical College Manipal",
    shortName: "KMC Manipal",
    stream: "Medical & Bio",
    city: "Manipal",
    state: "Karnataka",
    type: "Top Private",
    nirfRank: 9,
    annualFeesEstimate: "₹17.5 Lakhs / yr",
    medianCtcEstimate: "₹15.5 LPA",
    admissionExam: "NEET UG",
    rating: 4.8,
    highlight: "Ranked among India's top 10 medical colleges; world-renowned anatomy museum and USMLE preparation track record.",
    popularPrograms: ["MBBS", "B.Sc Medical Biotechnology", "MD / MS"],
    keyStrengths: ["Top USMLE match rates for US residencies", "Advanced simulation hospital", "Ranked #9 in NIRF Medical"],
    specializations: ["Cardiology", "Orthopedics", "Pathology", "Medical Research"],
  },

  // =========================================================================
  // 6. COMMERCE, BUSINESS & MANAGEMENT
  // =========================================================================
  {
    id: "srcc-delhi",
    name: "Shri Ram College of Commerce (University of Delhi)",
    shortName: "SRCC",
    stream: "Commerce & Business",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 11,
    annualFeesEstimate: "₹0.30 Lakhs / yr",
    medianCtcEstimate: "₹10.5 LPA",
    admissionExam: "CUET UG",
    rating: 5.0,
    highlight: "The undisputed capital of undergraduate commerce in India. Unrivaled finance, consulting, and banking placements.",
    popularPrograms: ["B.Com (Hons)", "B.A. (Hons) Economics", "Global Business Operations (GBO)"],
    keyStrengths: ["Highest undergrad consulting placements (McKinsey, BCG, Bain)", "Virtually 100% placement rate", "Extremely low DU fees (~₹30k/yr)"],
    specializations: ["Finance", "Investment Banking", "Economics", "Management Consulting", "Accounting"],
  },
  {
    id: "hindu-college-delhi",
    name: "Hindu College (University of Delhi)",
    shortName: "Hindu College",
    stream: "Commerce & Business",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 1,
    annualFeesEstimate: "₹0.25 Lakhs / yr",
    medianCtcEstimate: "₹10.0 LPA",
    admissionExam: "CUET UG",
    rating: 5.0,
    highlight: "Ranked #1 College in India by NIRF 2024/2025. Elite alumni in politics, bureaucracy, finance, and journalism.",
    popularPrograms: ["B.Com (Hons)", "B.A. (Hons) Economics", "B.Sc (Hons) Statistics"],
    keyStrengths: ["Ranked #1 College overall in India by NIRF", "Top consulting & analytics placements", "Vibrant North Campus society life"],
    specializations: ["Economics", "Finance", "Data Analytics", "Public Policy"],
  },
  {
    id: "sscbs-delhi",
    name: "Shaheed Sukhdev College of Business Studies (DU)",
    shortName: "SSCBS Delhi",
    stream: "Commerce & Business",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 42,
    annualFeesEstimate: "₹0.25 Lakhs / yr",
    medianCtcEstimate: "₹11.2 LPA",
    admissionExam: "CUET UG",
    rating: 4.9,
    highlight: "India's best undergraduate business school for BMS and BBA Financial & Investment Analysis (BFIA).",
    popularPrograms: ["Bachelor of Management Studies (BMS)", "BBA (Financial and Investment Analysis)", "B.Sc (Hons) Computer Science"],
    keyStrengths: ["Highest undergraduate management packages in India", "Consulting and investment banking hiring", "Rigorous case study pedagogy"],
    specializations: ["Investment Banking", "Corporate Finance", "Management Consulting", "Fintech"],
  },
  {
    id: "st-xaviers-mumbai",
    name: "St. Xavier's College (Autonomous) Mumbai",
    shortName: "St. Xavier's Mumbai",
    stream: "Commerce & Business",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Top Private",
    nirfRank: 87,
    annualFeesEstimate: "₹0.40 Lakhs / yr",
    medianCtcEstimate: "₹7.5 LPA",
    admissionExam: "XET / Merit",
    rating: 4.8,
    highlight: "Iconic neo-Gothic heritage campus in South Mumbai; premier Bachelor of Management Studies (BMS) and Economics.",
    popularPrograms: ["Bachelor of Management Studies (BMS)", "B.A. Economics", "B.Sc Statistics"],
    keyStrengths: ["South Mumbai financial capital location", "Malhar cultural fest", "Strong media & financial ties"],
    specializations: ["Marketing", "Finance", "Economics", "Advertising"],
  },
  {
    id: "christ-bangalore",
    name: "Christ (Deemed to be University) Bangalore",
    shortName: "Christ University",
    stream: "Commerce & Business",
    city: "Bengaluru",
    state: "Karnataka",
    type: "Top Private",
    nirfRank: 60,
    annualFeesEstimate: "₹2.2 Lakhs / yr",
    medianCtcEstimate: "₹7.0 LPA",
    admissionExam: "Christ University Entrance Test (CUET)",
    rating: 4.6,
    highlight: "Famous for BBA (Finance/Analytics) and B.Com Professional. High placement rate across Big 4 accounting and MNCs.",
    popularPrograms: ["BBA (Decision Science & Analytics)", "B.Com (Finance & Accountancy)", "BBA (Finance & International Business)"],
    keyStrengths: ["Bengaluru corporate headquarters network", "Big 4 accounting firm campus recruitment", "Strict professional discipline"],
    specializations: ["Business Analytics", "Corporate Finance", "Human Resources", "Marketing"],
  },
  {
    id: "nmims-mumbai",
    name: "NMIMS Anil Surendra Modi School of Commerce",
    shortName: "NMIMS Mumbai",
    stream: "Commerce & Business",
    city: "Mumbai",
    state: "Maharashtra",
    type: "Top Private",
    nirfRank: 47,
    annualFeesEstimate: "₹3.5 Lakhs / yr",
    medianCtcEstimate: "₹8.2 LPA",
    admissionExam: "NPAT",
    rating: 4.6,
    highlight: "High-flying Mumbai business school with rigorous curriculum in BBA, B.Com (Hons), and B.Sc Finance.",
    popularPrograms: ["BBA", "B.Sc Finance", "B.Com (Hons)"],
    keyStrengths: ["Direct connection with Mumbai financial firms", "High corporate networking", "Strong BFSI recruitment"],
    specializations: ["Corporate Finance", "Fintech", "Marketing", "Wealth Management"],
  },

  // =========================================================================
  // 7. LAW & PUBLIC POLICY
  // =========================================================================
  {
    id: "nlsiu-bangalore",
    name: "National Law School of India University",
    shortName: "NLSIU Bangalore",
    stream: "Law",
    city: "Bengaluru",
    state: "Karnataka",
    type: "NLU / Law",
    nirfRank: 1,
    annualFeesEstimate: "₹3.5 Lakhs / yr",
    medianCtcEstimate: "₹18.0 LPA",
    admissionExam: "CLAT",
    rating: 5.0,
    highlight: "Ranked #1 Law School in India every single year. The Harvard Law of India; top corporate law and judicial clerkships.",
    popularPrograms: ["B.A. LL.B. (Hons)", "LL.M.", "Master of Public Policy (MPP)"],
    keyStrengths: ["Ranked #1 in NIRF Law consistently", "Top tier Magic Circle & Indian corporate law placements", "Unbeatable moot court record"],
    specializations: ["Corporate Law", "Mergers & Acquisitions", "International Law", "Constitutional Law", "Public Policy"],
  },
  {
    id: "nalsar-hyderabad",
    name: "NALSAR University of Law",
    shortName: "NALSAR Hyderabad",
    stream: "Law",
    city: "Hyderabad",
    state: "Telangana",
    type: "NLU / Law",
    nirfRank: 3,
    annualFeesEstimate: "₹2.8 Lakhs / yr",
    medianCtcEstimate: "₹16.5 LPA",
    admissionExam: "CLAT",
    rating: 4.9,
    highlight: "Magnificent residential campus in Shameerpet; elite faculty in commercial, constitutional, and aviation law.",
    popularPrograms: ["B.A. LL.B. (Hons)", "BBA LL.B. (Hons)", "LL.M."],
    keyStrengths: ["Top tier corporate law firm hiring", "Centre for Aerospace and Defence Laws", "Vibrant campus culture"],
    specializations: ["Corporate Law", "Arbitration", "Aviation Law", "Intellectual Property"],
  },
  {
    id: "nlu-delhi",
    name: "National Law University Delhi",
    shortName: "NLU Delhi",
    stream: "Law",
    city: "New Delhi",
    state: "Delhi",
    type: "NLU / Law",
    nirfRank: 2,
    annualFeesEstimate: "₹3.2 Lakhs / yr",
    medianCtcEstimate: "₹17.0 LPA",
    admissionExam: "AILET",
    rating: 4.9,
    highlight: "Capital city NLU with supreme proximity to the Supreme Court of India, law ministries, and top law firms.",
    popularPrograms: ["B.A. LL.B. (Hons)", "LL.M.", "Ph.D in Law"],
    keyStrengths: ["Supreme Court of India proximity & internships", "Dedicated entrance via AILET", "Elite legal research centres"],
    specializations: ["Constitutional Law", "Criminal Justice", "Competition Law", "Corporate Law"],
  },
  {
    id: "wbnujs-kolkata",
    name: "West Bengal National University of Juridical Sciences",
    shortName: "WBNUJS Kolkata",
    stream: "Law",
    city: "Kolkata",
    state: "West Bengal",
    type: "NLU / Law",
    nirfRank: 4,
    annualFeesEstimate: "₹2.9 Lakhs / yr",
    medianCtcEstimate: "₹15.5 LPA",
    admissionExam: "CLAT",
    rating: 4.8,
    highlight: "Founded with guidance from Justice Chittatosh Mookerjee; stellar domestic and international law firm recruitment.",
    popularPrograms: ["B.A. LL.B. (Hons)", "B.Sc LL.B. (Hons)", "LL.M."],
    keyStrengths: ["High-density corporate placements", "Pioneering B.Sc LL.B. forensic track", "Active legal aid clinic"],
    specializations: ["Commercial Law", "Banking & Finance Law", "IPR", "Technology Law"],
  },
  {
    id: "jindal-law-school",
    name: "Jindal Global Law School (O.P. Jindal)",
    shortName: "JGLS Sonepat",
    stream: "Law",
    city: "Sonipat",
    state: "Haryana",
    type: "Top Private",
    nirfRank: 50,
    annualFeesEstimate: "₹6.5 Lakhs / yr",
    medianCtcEstimate: "₹12.5 LPA",
    admissionExam: "LSAT—India",
    rating: 4.7,
    highlight: "Global faculty from Oxford, Harvard, and Yale; world-class residential campus with international law pathways.",
    popularPrograms: ["B.A. LL.B. (Hons)", "BBA LL.B. (Hons)", "LL.B. (3 Years)"],
    keyStrengths: ["Ranked #1 Private Law School in India by QS World Rankings", "Massive international faculty", "Corporate law partnerships"],
    specializations: ["Corporate Law", "International Arbitration", "Human Rights", "Entertainment Law"],
  },

  // =========================================================================
  // 8. DESIGN & MEDIA
  // =========================================================================
  {
    id: "nid-ahmedabad",
    name: "National Institute of Design Ahmedabad",
    shortName: "NID Ahmedabad",
    stream: "Design & Media",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "National Institute",
    nirfRank: 1,
    annualFeesEstimate: "₹3.8 Lakhs / yr",
    medianCtcEstimate: "₹14.0 LPA",
    admissionExam: "NID DAT (Prelims + Mains)",
    rating: 5.0,
    highlight: "Institute of National Importance. India's premier design destination for Product Design, Graphic Design, and Interaction Design.",
    popularPrograms: ["B.Des Product Design", "B.Des Graphic Design", "B.Des Film & Video Communication"],
    keyStrengths: ["Institute of National Importance", "Top UX & Product Design offers from Google, Apple, Microsoft", "Heritage Charles Eames legacy"],
    specializations: ["Product Design", "UX/UI Design", "Interaction Design", "Animation", "Film & Video"],
  },
  {
    id: "iit-bombay-idc",
    name: "Industrial Design Centre (IDC), IIT Bombay",
    shortName: "IDC IIT Bombay",
    stream: "Design & Media",
    city: "Mumbai",
    state: "Maharashtra",
    type: "IIT",
    nirfRank: 3,
    annualFeesEstimate: "₹2.5 Lakhs / yr",
    medianCtcEstimate: "₹18.0 LPA",
    admissionExam: "UCEED",
    rating: 4.9,
    highlight: "Premier design institute combining world-class engineering, cognitive science, and human-computer interaction.",
    popularPrograms: ["B.Des (Bachelor of Design)", "M.Des Interaction Design", "M.Des Mobility & Vehicle Design"],
    keyStrengths: ["Highest paying design placements in India", "Human-Computer Interaction leadership", "Direct immersion in IIT Bombay tech"],
    specializations: ["Interaction Design", "UX/UI Design", "Automotive Design", "Visual Communication"],
  },
  {
    id: "nift-delhi",
    name: "National Institute of Fashion Technology New Delhi",
    shortName: "NIFT Delhi",
    stream: "Design & Media",
    city: "New Delhi",
    state: "Delhi",
    type: "National Institute",
    nirfRank: 1,
    annualFeesEstimate: "₹3.2 Lakhs / yr",
    medianCtcEstimate: "₹7.5 LPA",
    admissionExam: "NIFT Entrance Exam",
    rating: 4.8,
    highlight: "Flagship NIFT campus in Hauz Khas. Pioneer in Fashion Design, Fashion Communication, and Textile Design.",
    popularPrograms: ["B.Des Fashion Design", "B.Des Fashion Communication", "B.F.Tech Apparel Production"],
    keyStrengths: ["Ranked #1 Fashion & Design institute in India", "Central Delhi creative hub", "Global fashion house partnerships"],
    specializations: ["Fashion Design", "Fashion Communication", "Brand Management", "Styling & Media"],
  },
  {
    id: "srishti-bangalore",
    name: "Srishti Manipal Institute of Art, Design and Technology",
    shortName: "Srishti Bangalore",
    stream: "Design & Media",
    city: "Bengaluru",
    state: "Karnataka",
    type: "Top Private",
    nirfRank: "Top Creative",
    annualFeesEstimate: "₹5.0 Lakhs / yr",
    medianCtcEstimate: "₹8.0 LPA",
    admissionExam: "Srishti Entrance (SMEAT)",
    rating: 4.6,
    highlight: "Experimental and contemporary art, creative media, and digital experience design school in Yelahanka, Bengaluru.",
    popularPrograms: ["B.Des Human Centered Design", "B.Des Creative & Applied Arts", "B.Voc Digital Media"],
    keyStrengths: ["High freedom of creative projects", "Bengaluru creative tech ecosystem", "Focus on speculative design"],
    specializations: ["UX Design", "Digital Media", "Game Design", "Spatial Design"],
  },
  {
    id: "iimc-delhi",
    name: "Indian Institute of Mass Communication",
    shortName: "IIMC Delhi",
    stream: "Design & Media",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 1,
    annualFeesEstimate: "₹0.90 Lakhs / yr",
    medianCtcEstimate: "₹6.5 LPA",
    admissionExam: "CUET PG / IIMC Entrance",
    rating: 4.8,
    highlight: "Premier journalism, digital broadcasting, and advertising institute under the Ministry of Information & Broadcasting.",
    popularPrograms: ["PG Diploma in Journalism", "PG Diploma in Radio & TV", "PG Diploma in Advertising & PR"],
    keyStrengths: ["Autonomous body under Ministry of I&B", "Alma mater of India's leading broadcast editors", "Top media house recruitment"],
    specializations: ["Digital Journalism", "Broadcast Media", "Public Relations", "Advertising"],
  }
];
