export interface CollegeProfile {
  id: string;
  name: string;
  shortName: string;
  stream: "Science & Tech" | "Commerce & Business" | "Arts & Humanities" | "Law" | "Design & Media" | "Medical & Bio";
  city: string;
  state: string;
  type: "IIT" | "NIT / IIIT" | "Central University" | "Top Private" | "State Govt" | "National Institute";
  nirfRank: number | string;
  annualFeesEstimate: string;
  medianCtcEstimate: string;
  admissionExam: string;
  rating: number;
  highlight: string;
  popularPrograms: string[];
  keyStrengths: string[];
}

export const COLLEGE_DIRECTORY: CollegeProfile[] = [
  // Science & Tech
  {
    id: "iit-bombay",
    name: "Indian Institute of Technology Bombay",
    shortName: "IIT Bombay",
    stream: "Science & Tech",
    city: "Mumbai",
    state: "Maharashtra",
    type: "IIT",
    nirfRank: 3,
    annualFeesEstimate: "₹2.5 Lakhs / yr",
    medianCtcEstimate: "₹21.8 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.9,
    highlight: "India's premier engineering destination with world-class entrepreneurship and tech ecosystem.",
    popularPrograms: ["B.Tech Computer Science", "Electrical Engineering", "BS Mathematics"],
    keyStrengths: ["Top Silicon Valley & Mumbai placements", "E-Cell startup hub", "Global faculty network"],
  },
  {
    id: "iit-delhi",
    name: "Indian Institute of Technology Delhi",
    shortName: "IIT Delhi",
    stream: "Science & Tech",
    city: "New Delhi",
    state: "Delhi",
    type: "IIT",
    nirfRank: 2,
    annualFeesEstimate: "₹2.4 Lakhs / yr",
    medianCtcEstimate: "₹20.5 LPA",
    admissionExam: "JEE Advanced",
    rating: 4.9,
    highlight: "Unrivaled research impact, central capital location, and top venture capital pedigree.",
    popularPrograms: ["B.Tech CSE", "B.Tech Mathematics & Computing", "Biotechnology"],
    keyStrengths: ["Highest unicorn founder output", "Deep industry research alliances", "Hauz Khas connectivity"],
  },
  {
    id: "bits-pilani",
    name: "Birla Institute of Technology and Science, Pilani",
    shortName: "BITS Pilani",
    stream: "Science & Tech",
    city: "Pilani",
    state: "Rajasthan",
    type: "Top Private",
    nirfRank: 20,
    annualFeesEstimate: "₹5.5 Lakhs / yr",
    medianCtcEstimate: "₹18.5 LPA",
    admissionExam: "BITSAT",
    rating: 4.8,
    highlight: "Zero attendance policy, flexible dual-degree programs, and a peer network rivaling top IITs.",
    popularPrograms: ["B.E. Computer Science", "B.E. Electrical & Electronics", "M.Sc Dual Degree"],
    keyStrengths: ["Practice School (6-month paid corporate internship)", "No caste reservations / pure merit", "Global alumni fund"],
  },
  {
    id: "nit-trichy",
    name: "National Institute of Technology Tiruchirappalli",
    shortName: "NIT Trichy",
    stream: "Science & Tech",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    type: "NIT / IIIT",
    nirfRank: 9,
    annualFeesEstimate: "₹1.8 Lakhs / yr",
    medianCtcEstimate: "₹14.5 LPA",
    admissionExam: "JEE Main",
    rating: 4.7,
    highlight: "Ranked #1 among all 31 National Institutes of Technology across India.",
    popularPrograms: ["B.Tech CSE", "B.Tech Mechanical", "Instrumentation & Control"],
    keyStrengths: ["High ROI government fee structure", "Consistent Tier-1 recruiting", "800-acre lush campus"],
  },
  {
    id: "iiit-hyderabad",
    name: "International Institute of Information Technology Hyderabad",
    shortName: "IIIT Hyderabad",
    stream: "Science & Tech",
    city: "Hyderabad",
    state: "Telangana",
    type: "Top Private",
    nirfRank: 55,
    annualFeesEstimate: "₹4.0 Lakhs / yr",
    medianCtcEstimate: "₹30.0 LPA",
    admissionExam: "JEE Main / UGEE",
    rating: 4.9,
    highlight: "India's undisputed leader in Computer Science research, NLP, Computer Vision, and Competitive Programming.",
    popularPrograms: ["B.Tech CSE", "B.Tech Computer Science + MS Dual Degree", "ECD"],
    keyStrengths: ["Median packages surpassing older IITs", "World-renowned Kohler Hall AI labs", "High GSoC selection counts"],
  },

  // Commerce & Business
  {
    id: "srcc-delhi",
    name: "Shri Ram College of Commerce (DU)",
    shortName: "SRCC",
    stream: "Commerce & Business",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 11,
    annualFeesEstimate: "₹35,000 / yr",
    medianCtcEstimate: "₹10.5 LPA",
    admissionExam: "CUET UG",
    rating: 4.9,
    highlight: "The holy grail of undergraduate commerce education in Asia. Massive alumni presence across Dalal Street and civil services.",
    popularPrograms: ["B.Com (Honours)", "B.A. (Hons) Economics"],
    keyStrengths: ["Highest undergrad consulting placements (McKinsey, BCG, Bain)", "Virtually free tuition fees", "Iconic North Campus ecosystem"],
  },
  {
    id: "st-xaviers-mumbai",
    name: "St. Xavier's College (Autonomous)",
    shortName: "St. Xavier's Mumbai",
    stream: "Commerce & Business",
    city: "Mumbai",
    state: "Maharashtra",
    type: "State Govt",
    nirfRank: 89,
    annualFeesEstimate: "₹40,000 / yr",
    medianCtcEstimate: "₹7.5 LPA",
    admissionExam: "XET / 12th Merit",
    rating: 4.6,
    highlight: "Gothic architecture, vibrant media and finance societies, and unmatched Mumbai industry proximity.",
    popularPrograms: ["Bachelor of Management Studies (BMS)", "B.Com", "BA Economics"],
    keyStrengths: ["South Mumbai corporate access", "Malhar cultural festival", "High prestige in consulting and media"],
  },
  {
    id: "loyola-chennai",
    name: "Loyola College",
    shortName: "Loyola College Chennai",
    stream: "Commerce & Business",
    city: "Chennai",
    state: "Tamil Nadu",
    type: "State Govt",
    nirfRank: 8,
    annualFeesEstimate: "₹45,000 / yr",
    medianCtcEstimate: "₹6.8 LPA",
    admissionExam: "12th Merit / Entrance",
    rating: 4.7,
    highlight: "A premier minority institution known for academic discipline and outstanding corporate connections.",
    popularPrograms: ["B.Com General", "BBA", "B.A. Economics"],
    keyStrengths: ["Consistently in top 10 NIRF College category", "Strong commerce faculty", "Diverse national student base"],
  },
  {
    id: "iim-indore-ipm",
    name: "Indian Institute of Management Indore (IPM)",
    shortName: "IIM Indore",
    stream: "Commerce & Business",
    city: "Indore",
    state: "Madhya Pradesh",
    type: "National Institute",
    nirfRank: 8,
    annualFeesEstimate: "₹7.0 Lakhs / yr (Undergrad)",
    medianCtcEstimate: "₹25.6 LPA (Post-MBA)",
    admissionExam: "IPMAT",
    rating: 4.8,
    highlight: "First IIM to offer direct 5-year integrated management degree straight after 12th board exams.",
    popularPrograms: ["Integrated Programme in Management (BBA+MBA)"],
    keyStrengths: ["IIM brand identity straight out of school", "No need to sit for CAT exam", "Elite corporate leadership pipeline"],
  },

  // Arts & Humanities
  {
    id: "st-stephens-delhi",
    name: "St. Stephen's College (DU)",
    shortName: "St. Stephen's",
    stream: "Arts & Humanities",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 14,
    annualFeesEstimate: "₹42,000 / yr",
    medianCtcEstimate: "₹9.2 LPA",
    admissionExam: "CUET UG",
    rating: 4.8,
    highlight: "India's most storied undergraduate liberal arts institution with unmatched political and literary tradition.",
    popularPrograms: ["B.A. (Hons) Economics", "B.A. (Hons) History", "B.A. (Hons) English"],
    keyStrengths: ["Rhodes Scholar pipeline", "North Campus elite intellectual network", "Stephanian alumni network"],
  },
  {
    id: "lsr-delhi",
    name: "Lady Shri Ram College for Women (DU)",
    shortName: "LSR College",
    stream: "Arts & Humanities",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 9,
    annualFeesEstimate: "₹30,000 / yr",
    medianCtcEstimate: "₹8.5 LPA",
    admissionExam: "CUET UG",
    rating: 4.8,
    highlight: "The benchmark for women's leadership, social sciences, journalism, and public policy in India.",
    popularPrograms: ["B.A. (Hons) Political Science", "B.A. (Hons) Psychology", "B.A. (Hons) Journalism"],
    keyStrengths: ["Top civil service preparation ground", "High placements in consulting and NGO policy", "Lajpat Nagar South Delhi campus"],
  },
  {
    id: "miranda-house",
    name: "Miranda House (DU)",
    shortName: "Miranda House",
    stream: "Arts & Humanities",
    city: "New Delhi",
    state: "Delhi",
    type: "Central University",
    nirfRank: 1,
    annualFeesEstimate: "₹28,000 / yr",
    medianCtcEstimate: "₹7.8 LPA",
    admissionExam: "CUET UG",
    rating: 4.9,
    highlight: "Ranked #1 College in India by NIRF for 7 consecutive years across all disciplines.",
    popularPrograms: ["B.A. (Hons) English", "B.A. (Hons) Geography", "B.A. (Hons) Sociology"],
    keyStrengths: ["Consistently top NIRF score", "High research output and vibrant societies", "Pristine heritage campus"],
  },

  // Law
  {
    id: "nlsiu-bengaluru",
    name: "National Law School of India University",
    shortName: "NLSIU Bengaluru",
    stream: "Law",
    city: "Bengaluru",
    state: "Karnataka",
    type: "National Institute",
    nirfRank: 1,
    annualFeesEstimate: "₹3.8 Lakhs / yr",
    medianCtcEstimate: "₹18.0 LPA",
    admissionExam: "CLAT UG",
    rating: 5.0,
    highlight: "The undisputed Harvard of Indian legal education, founding father of the modern NLU model.",
    popularPrograms: ["B.A. LL.B. (Hons)", "Public Policy"],
    keyStrengths: ["100% Day-1 placement at Tier-1 law firms (Cyril Amarchand, Shardul, Trilegal, Khaitan)", "High judicial clerkships & Supreme Court Bar leaders", "Nagarbhavi lush campus"],
  },
  {
    id: "nalsar-hyderabad",
    name: "NALSAR University of Law",
    shortName: "NALSAR Hyderabad",
    stream: "Law",
    city: "Hyderabad",
    state: "Telangana",
    type: "National Institute",
    nirfRank: 3,
    annualFeesEstimate: "₹3.2 Lakhs / yr",
    medianCtcEstimate: "₹16.5 LPA",
    admissionExam: "CLAT UG",
    rating: 4.8,
    highlight: "Renowned for international moot court victories, corporate law excellence, and progressive campus freedom.",
    popularPrograms: ["B.A. LL.B. (Hons)", "IPR & Cyber Law"],
    keyStrengths: ["Shamirpet lake campus", "Top domestic and Magic Circle UK firm recruitment", "Leading academic faculty"],
  },

  // Design & Media
  {
    id: "nid-ahmedabad",
    name: "National Institute of Design",
    shortName: "NID Ahmedabad",
    stream: "Design & Media",
    city: "Ahmedabad",
    state: "Gujarat",
    type: "National Institute",
    nirfRank: "Institute of National Importance",
    annualFeesEstimate: "₹3.5 Lakhs / yr",
    medianCtcEstimate: "₹14.0 LPA",
    admissionExam: "NID DAT",
    rating: 4.9,
    highlight: "Created with Charles & Ray Eames manifesto, NID is India's most celebrated design school with global standing.",
    popularPrograms: ["B.Des Product Design", "B.Des Communication Design", "B.Des Animation"],
    keyStrengths: ["High demand in tech product design & UX", "Heritage Paldi campus", "Alumni heading global design studios"],
  },
  {
    id: "iit-bombay-idc",
    name: "Industrial Design Centre (IDC) - IIT Bombay",
    shortName: "IDC IIT Bombay",
    stream: "Design & Media",
    city: "Mumbai",
    state: "Maharashtra",
    type: "IIT",
    nirfRank: "Top Tier",
    annualFeesEstimate: "₹2.2 Lakhs / yr",
    medianCtcEstimate: "₹18.2 LPA",
    admissionExam: "UCEED",
    rating: 4.9,
    highlight: "Bridges high-tech engineering with human-centered product and interaction design.",
    popularPrograms: ["Bachelor of Design (B.Des)", "Interaction Design", "Mobility & Vehicle Design"],
    keyStrengths: ["IIT Bombay alumni privilege", "Tech-product hybrid recruiting", "State of the art rapid prototyping labs"],
  },

  // Medical & Bio
  {
    id: "aiims-delhi",
    name: "All India Institute of Medical Sciences",
    shortName: "AIIMS New Delhi",
    stream: "Medical & Bio",
    city: "New Delhi",
    state: "Delhi",
    type: "National Institute",
    nirfRank: 1,
    annualFeesEstimate: "₹1,628 / yr (Virtually Free)",
    medianCtcEstimate: "Govt Stipend / Global MD",
    admissionExam: "NEET UG",
    rating: 5.0,
    highlight: "India's highest pinnacle of medical education, clinical research, and tertiary healthcare.",
    popularPrograms: ["MBBS", "B.Sc Nursing", "Biochemistry"],
    keyStrengths: ["Unrivaled clinical exposure", "Almost zero tuition expenditure", "Direct USMLE/PLAB success rate"],
  },
  {
    id: "cmc-vellore",
    name: "Christian Medical College",
    shortName: "CMC Vellore",
    stream: "Medical & Bio",
    city: "Vellore",
    state: "Tamil Nadu",
    type: "Top Private",
    nirfRank: 3,
    annualFeesEstimate: "₹50,000 / yr",
    medianCtcEstimate: "Govt Stipend / MD Path",
    admissionExam: "NEET UG",
    rating: 4.8,
    highlight: "Pioneered India's first open-heart surgery, world-renowned for patient empathy and medical ethics.",
    popularPrograms: ["MBBS", "Allied Health Sciences"],
    keyStrengths: ["Subsidized education", "High international medical standing", "Exemplary healthcare mission"],
  },
];
