export interface EntranceExam {
  id: string;
  name: string;
  shortName: string;
  stream: "Engineering" | "Medical" | "Commerce & Management" | "Law" | "Design & Arts" | "Defense & Civil";
  conductingBody: string;
  eligibility: string;
  annualApplicants: string;
  examMonth: string;
  examDateEstimate: string;
  applicationDeadline: string;
  status: "Registration Open" | "Upcoming" | "Announced" | "In Progress";
  officialUrl: string;
  keySubjects: string[];
  description: string;
  seatsOffered: string;
  difficultyRating: number; // 1 to 5
}

export const ENTRANCE_EXAMS: EntranceExam[] = [
  // =========================================================================
  // 1. ENGINEERING & TECH EXAMS
  // =========================================================================
  {
    id: "jee-main",
    name: "Joint Entrance Examination (Main)",
    shortName: "JEE Main",
    stream: "Engineering",
    conductingBody: "National Testing Agency (NTA)",
    eligibility: "Class 12 pass or appearing with Physics, Mathematics, and Chemistry/Tech subject",
    annualApplicants: "14.2+ Lakhs",
    examMonth: "January & April",
    examDateEstimate: "Session 1: Jan 22 - Jan 31 | Session 2: Apr 1 - Apr 8",
    applicationDeadline: "Session 1: Late Nov | Session 2: Late Feb",
    status: "Registration Open",
    officialUrl: "https://jeemain.nta.nic.in",
    keySubjects: ["Physics", "Chemistry", "Mathematics"],
    description: "National gateway for admission to 31 NITs, 26 IIITs, and government CFTIs, and cutoff qualifier for JEE Advanced.",
    seatsOffered: "60,000+ across NITs / IIITs / GFTIs",
    difficultyRating: 4.5,
  },
  {
    id: "jee-advanced",
    name: "Joint Entrance Examination (Advanced)",
    shortName: "JEE Advanced",
    stream: "Engineering",
    conductingBody: "IIT Kanpur / Rotational IIT",
    eligibility: "Top 2,50,000 qualifiers of JEE Main (Paper 1)",
    annualApplicants: "2.5 Lakhs (Capped)",
    examMonth: "May",
    examDateEstimate: "Sunday, May 18 - May 25",
    applicationDeadline: "Early May",
    status: "Upcoming",
    officialUrl: "https://jeeadv.ac.in",
    keySubjects: ["Advanced Physics", "Advanced Chemistry", "Advanced Mathematics"],
    description: "The premier entrance examination for admission into B.Tech and Dual Degree programs across all 23 Indian Institutes of Technology (IITs).",
    seatsOffered: "17,700+ IIT Seats",
    difficultyRating: 5.0,
  },
  {
    id: "bitsat",
    name: "BITS Admission Test",
    shortName: "BITSAT",
    stream: "Engineering",
    conductingBody: "BITS Pilani",
    eligibility: "75% aggregate in PCM in 12th board with at least 60% in each subject",
    annualApplicants: "3.2+ Lakhs",
    examMonth: "May & June",
    examDateEstimate: "Session 1: May 20 - May 26 | Session 2: June 22 - June 26",
    applicationDeadline: "Session 1: Mid April | Session 2: Early June",
    status: "Registration Open",
    officialUrl: "https://www.bitsadmission.com",
    keySubjects: ["Physics", "Chemistry", "Mathematics", "Logical Reasoning", "English"],
    description: "Computer-based online exam for admissions into B.E., M.Sc Dual, and B.Pharm across BITS Pilani, Goa, and Hyderabad campuses.",
    seatsOffered: "3,200+ across 3 campuses",
    difficultyRating: 4.2,
  },
  {
    id: "viteee",
    name: "VIT Engineering Entrance Examination",
    shortName: "VITEEE",
    stream: "Engineering",
    conductingBody: "Vellore Institute of Technology",
    eligibility: "60% aggregate in Physics, Chemistry, and Mathematics/Biology in Class 12",
    annualApplicants: "2.5+ Lakhs",
    examMonth: "April",
    examDateEstimate: "April 19 - April 30",
    applicationDeadline: "End of March",
    status: "Registration Open",
    officialUrl: "https://viteee.vit.ac.in",
    keySubjects: ["Maths / Bio", "Physics", "Chemistry", "English", "Aptitude"],
    description: "Online test for B.Tech admissions across VIT Vellore, VIT Chennai, VIT AP, and VIT Bhopal campuses.",
    seatsOffered: "12,000+ across all VIT campuses",
    difficultyRating: 3.8,
  },
  {
    id: "comedk-uget",
    name: "Consortium of Medical, Engineering and Dental Colleges of Karnataka",
    shortName: "COMEDK UGET",
    stream: "Engineering",
    conductingBody: "COMEDK Karnataka",
    eligibility: "Class 12 pass with 45% in PCM",
    annualApplicants: "1.1+ Lakhs",
    examMonth: "May",
    examDateEstimate: "Second Sunday of May",
    applicationDeadline: "Early April",
    status: "Upcoming",
    officialUrl: "https://www.comedk.org",
    keySubjects: ["Physics", "Chemistry", "Mathematics"],
    description: "National centralized test for admission to 190+ top private engineering institutions in Karnataka including RVCE, BMSCE, and MSRIT.",
    seatsOffered: "20,000+ Engineering Seats",
    difficultyRating: 3.9,
  },
  {
    id: "met-manipal",
    name: "Manipal Entrance Test",
    shortName: "MET",
    stream: "Engineering",
    conductingBody: "Manipal Academy of Higher Education (MAHE)",
    eligibility: "Class 12 pass with 50% in PCM",
    annualApplicants: "80,000+",
    examMonth: "April & May",
    examDateEstimate: "Phase 1: Mid April | Phase 2: Mid May",
    applicationDeadline: "Mid March",
    status: "Registration Open",
    officialUrl: "https://manipal.edu/met",
    keySubjects: ["Mathematics", "Physics", "Chemistry", "English"],
    description: "Admission pathway for B.Tech programs at Manipal Institute of Technology (MIT Manipal, Bengaluru, and Jaipur).",
    seatsOffered: "3,500+ Engineering Seats",
    difficultyRating: 3.8,
  },
  {
    id: "wbjee",
    name: "West Bengal Joint Entrance Examination",
    shortName: "WBJEE",
    stream: "Engineering",
    conductingBody: "WBJEE Board",
    eligibility: "Class 12 pass with Physics and Mathematics along with one technical subject",
    annualApplicants: "1.2+ Lakhs",
    examMonth: "April",
    examDateEstimate: "Last Sunday of April",
    applicationDeadline: "Early February",
    status: "Announced",
    officialUrl: "https://wbjeeb.nic.in",
    keySubjects: ["Mathematics (100 Marks)", "Physics & Chemistry (100 Marks)"],
    description: "State level gateway for premier institutions like Jadavpur University, Calcutta University, and top private engineering colleges.",
    seatsOffered: "35,000+ Engineering Seats",
    difficultyRating: 4.1,
  },

  // =========================================================================
  // 2. MEDICAL & HEALTHCARE EXAMS
  // =========================================================================
  {
    id: "neet-ug",
    name: "National Eligibility cum Entrance Test (UG)",
    shortName: "NEET UG",
    stream: "Medical",
    conductingBody: "National Testing Agency (NTA)",
    eligibility: "Class 12 with Physics, Chemistry, Biology/Biotech with minimum 50% marks (General)",
    annualApplicants: "24.5+ Lakhs",
    examMonth: "May",
    examDateEstimate: "First Sunday of May",
    applicationDeadline: "Early March",
    status: "Upcoming",
    officialUrl: "https://neet.nta.nic.in",
    keySubjects: ["Biology (Botany + Zoology)", "Physics", "Chemistry"],
    description: "Single unified entrance examination for MBBS, BDS, BAMS, BHMS, and veterinary seats across India (including all AIIMS & JIPMER).",
    seatsOffered: "1,08,000+ MBBS Seats",
    difficultyRating: 4.8,
  },
  {
    id: "aiims-nursing",
    name: "AIIMS B.Sc (Hons) Nursing & Paramedical Entrance",
    shortName: "AIIMS B.Sc Nursing",
    stream: "Medical",
    conductingBody: "AIIMS New Delhi Exams Section",
    eligibility: "Class 12 with PCBE with 55% aggregate (Female candidates for B.Sc Hons)",
    annualApplicants: "1.5+ Lakhs",
    examMonth: "June",
    examDateEstimate: "First Weekend of June",
    applicationDeadline: "Mid April",
    status: "Upcoming",
    officialUrl: "https://aiimsexams.ac.in",
    keySubjects: ["Physics", "Chemistry", "Biology", "General Knowledge"],
    description: "Admission to 4-year B.Sc (Hons) Nursing across AIIMS New Delhi, Bhubaneswar, Bhopal, Jodhpur, and Rishikesh with guaranteed stipends.",
    seatsOffered: "1,200+ AIIMS Nursing Seats",
    difficultyRating: 4.0,
  },
  {
    id: "iat-iiser",
    name: "IISER Aptitude Test",
    shortName: "IAT",
    stream: "Medical",
    conductingBody: "IISER Joint Admissions Committee",
    eligibility: "Class 12 with at least 3 subjects out of PCMB",
    annualApplicants: "1.3+ Lakhs",
    examMonth: "June",
    examDateEstimate: "Second Sunday of June",
    applicationDeadline: "Mid May",
    status: "Upcoming",
    officialUrl: "https://iiseradmission.in",
    keySubjects: ["Physics", "Chemistry", "Mathematics", "Biology"],
    description: "Premier entrance exam for 5-year BS-MS dual degree pure science and research programs at IISERs (Pune, Kolkata, Mohali) and IISc Bangalore.",
    seatsOffered: "1,950+ Research Seats",
    difficultyRating: 4.6,
  },

  // =========================================================================
  // 3. COMMERCE, BUSINESS & MANAGEMENT EXAMS
  // =========================================================================
  {
    id: "cuet-ug",
    name: "Common University Entrance Test (UG)",
    shortName: "CUET UG",
    stream: "Commerce & Management",
    conductingBody: "National Testing Agency (NTA)",
    eligibility: "Class 12 pass from any recognized board",
    annualApplicants: "19.5+ Lakhs",
    examMonth: "May - June",
    examDateEstimate: "Mid May to Early June",
    applicationDeadline: "Early April",
    status: "Upcoming",
    officialUrl: "https://exams.nta.ac.in/CUET-UG",
    keySubjects: ["Domain Subjects", "General Aptitude Test", "English/Language"],
    description: "Unified national gateway for undergraduate admissions into Delhi University (SRCC, Hindu, LSR), BHU, JNU, and 250+ central & state universities.",
    seatsOffered: "3,50,000+ across participating universities",
    difficultyRating: 3.8,
  },
  {
    id: "ipmat",
    name: "Integrated Program in Management Aptitude Test",
    shortName: "IPMAT",
    stream: "Commerce & Management",
    conductingBody: "IIM Indore / IIM Rohtak",
    eligibility: "Minimum 60% in 10th and 12th standard",
    annualApplicants: "38,000+",
    examMonth: "May",
    examDateEstimate: "Third Week of May",
    applicationDeadline: "Early April",
    status: "Upcoming",
    officialUrl: "https://www.iimidr.ac.in",
    keySubjects: ["Quantitative Ability (MCQ + Short Answer)", "Verbal Ability"],
    description: "Direct 5-year dual degree (BBA + MBA) entry into elite Indian Institutes of Management (IIM Indore, Rohtak, Ranchi, Bodh Gaya, Jammu).",
    seatsOffered: "650+ across IIMs",
    difficultyRating: 4.4,
  },
  {
    id: "npat",
    name: "NMIMS Programs After Twelfth",
    shortName: "NPAT",
    stream: "Commerce & Management",
    conductingBody: "SVKM's NMIMS",
    eligibility: "Class 12 with 50% with Mathematics / Statistics for B.Sc Finance & BBA",
    annualApplicants: "75,000+",
    examMonth: "January to May (Rolling)",
    examDateEstimate: "Multiple booking slots through May 20",
    applicationDeadline: "First week of May",
    status: "Registration Open",
    officialUrl: "https://npat.nmims.edu",
    keySubjects: ["Quantitative Reasoning", "Logical Reasoning", "Verbal Reasoning"],
    description: "Entrance test for prestigious undergraduate business programs at Anil Surendra Modi School of Commerce (BBA, B.Com Hons, B.Sc Finance).",
    seatsOffered: "2,800+ across NMIMS campuses",
    difficultyRating: 3.8,
  },

  // =========================================================================
  // 4. LAW & PUBLIC POLICY EXAMS
  // =========================================================================
  {
    id: "clat",
    name: "Common Law Admission Test",
    shortName: "CLAT UG",
    stream: "Law",
    conductingBody: "Consortium of National Law Universities (NLUs)",
    eligibility: "Class 12 pass with minimum 45% (General/OBC)",
    annualApplicants: "70,000+",
    examMonth: "December",
    examDateEstimate: "First Sunday of December",
    applicationDeadline: "Late October",
    status: "Upcoming",
    officialUrl: "https://consortiumofnlus.ac.in",
    keySubjects: ["Legal Reasoning", "Current Affairs & GK", "Logical Reasoning", "English Language", "Quantitative Techniques"],
    description: "The primary entrance test for 5-year integrated BA/BBA LLB (Hons) across 24 premier National Law Universities (NLSIU Bengaluru, NALSAR, WBNUJS).",
    seatsOffered: "3,300+ NLU Seats",
    difficultyRating: 4.3,
  },
  {
    id: "ailet",
    name: "All India Law Entrance Test",
    shortName: "AILET",
    stream: "Law",
    conductingBody: "National Law University Delhi",
    eligibility: "Class 12 pass with minimum 45% marks",
    annualApplicants: "22,000+",
    examMonth: "December",
    examDateEstimate: "Second Sunday of December",
    applicationDeadline: "Mid November",
    status: "Upcoming",
    officialUrl: "https://nationallawuniversitydelhi.in",
    keySubjects: ["Logical Reasoning (70 Marks)", "English Language (50 Marks)", "Current Affairs (30 Marks)"],
    description: "Exclusive competitive test for admission to the prestigious 5-year B.A. LL.B. (Hons) program at National Law University Delhi.",
    seatsOffered: "123 Seats at NLU Delhi",
    difficultyRating: 4.6,
  },
  {
    id: "slat",
    name: "Symbiosis Law Aptitude Test",
    shortName: "SLAT",
    stream: "Law",
    conductingBody: "Symbiosis International (Deemed University)",
    eligibility: "Class 12 pass with minimum 45% marks",
    annualApplicants: "30,000+",
    examMonth: "May",
    examDateEstimate: "Test 1: May 5 | Test 2: May 11",
    applicationDeadline: "Mid April",
    status: "Registration Open",
    officialUrl: "https://set-test.org",
    keySubjects: ["Logical Reasoning", "Legal Reasoning", "Analytical Reasoning", "Reading Comprehension", "GK"],
    description: "Gateway for B.A. LL.B. (Hons) and BBA LL.B. (Hons) across Symbiosis Law Schools (SLS Pune, Noida, Hyderabad, Nagpur).",
    seatsOffered: "1,080+ Law Seats across SLS",
    difficultyRating: 3.9,
  },

  // =========================================================================
  // 5. DESIGN & ARCHITECTURE EXAMS
  // =========================================================================
  {
    id: "uceed",
    name: "Undergraduate Common Entrance Examination for Design",
    shortName: "UCEED",
    stream: "Design & Arts",
    conductingBody: "IIT Bombay",
    eligibility: "Class 12 pass from any stream (Science/Commerce/Arts)",
    annualApplicants: "16,000+",
    examMonth: "January",
    examDateEstimate: "Third Sunday of January",
    applicationDeadline: "Early November",
    status: "Announced",
    officialUrl: "https://uceed.iitb.ac.in",
    keySubjects: ["Visualization & Spatial Ability", "Observation & Design Sensitivity", "Analytical Reasoning", "Drawing Test"],
    description: "Entrance for Bachelor of Design (B.Des) at IIT Bombay, IIT Delhi, IIT Guwahati, IIT Hyderabad, and IIITDM Jabalpur.",
    seatsOffered: "225+ IIT B.Des seats",
    difficultyRating: 4.4,
  },
  {
    id: "nid-dat",
    name: "National Institute of Design - Design Aptitude Test",
    shortName: "NID DAT",
    stream: "Design & Arts",
    conductingBody: "National Institute of Design",
    eligibility: "Class 12 pass from any recognized board",
    annualApplicants: "22,000+",
    examMonth: "December / January",
    examDateEstimate: "Prelims: Late Dec | Mains: April",
    applicationDeadline: "Late November",
    status: "Announced",
    officialUrl: "https://admissions.nid.edu",
    keySubjects: ["Design Aptitude", "General Knowledge & Observation", "Studio Test & Personal Interview"],
    description: "India's most prestigious design school entrance for B.Des across NID Ahmedabad, Gandhinagar, Bengaluru, Kurukshetra, and Vijayawada.",
    seatsOffered: "425 B.Des seats",
    difficultyRating: 4.6,
  },
  {
    id: "nift-entrance",
    name: "National Institute of Fashion Technology Entrance Examination",
    shortName: "NIFT Entrance",
    stream: "Design & Arts",
    conductingBody: "National Testing Agency (NTA)",
    eligibility: "Class 12 pass from any recognized board",
    annualApplicants: "35,000+",
    examMonth: "February",
    examDateEstimate: "First Sunday of February",
    applicationDeadline: "Early January",
    status: "Announced",
    officialUrl: "https://nift.ac.in",
    keySubjects: ["General Ability Test (GAT)", "Creative Ability Test (CAT)", "Situation Test"],
    description: "Gateway to B.Des and B.F.Tech programs across 18 premier NIFT campuses including Delhi, Mumbai, and Bengaluru.",
    seatsOffered: "4,000+ Design Seats",
    difficultyRating: 4.1,
  },
  {
    id: "nata",
    name: "National Aptitude Test in Architecture",
    shortName: "NATA",
    stream: "Design & Arts",
    conductingBody: "Council of Architecture (CoA)",
    eligibility: "12th with Physics, Chemistry & Mathematics or 10+3 Diploma with Mathematics",
    annualApplicants: "55,000+",
    examMonth: "April - July (Multiple Attempts)",
    examDateEstimate: "Every weekend from April to July",
    applicationDeadline: "Rolling registration through June",
    status: "Registration Open",
    officialUrl: "https://www.nata.in",
    keySubjects: ["Drawing & Composition", "Visual Perception & Architectural Awareness", "Mathematics"],
    description: "National benchmark test required for admission to 5-year B.Arch programs across all recognized architecture colleges in India.",
    seatsOffered: "25,000+ B.Arch seats",
    difficultyRating: 3.7,
  },

  // =========================================================================
  // 6. DEFENSE & CIVIL SERVICES EXAMS
  // =========================================================================
  {
    id: "nda-na",
    name: "National Defence Academy & Naval Academy Examination",
    shortName: "NDA / NA",
    stream: "Defense & Civil",
    conductingBody: "Union Public Service Commission (UPSC)",
    eligibility: "Unmarried male & female candidates, 12th pass (Physics & Math for Air Force/Navy)",
    annualApplicants: "6.5+ Lakhs",
    examMonth: "April (NDA I) & September (NDA II)",
    examDateEstimate: "NDA I: Mid April | NDA II: Early Sept",
    applicationDeadline: "Jan (NDA I) | June (NDA II)",
    status: "Upcoming",
    officialUrl: "https://upsc.gov.in",
    keySubjects: ["Mathematics (300 Marks)", "General Ability Test (600 Marks)"],
    description: "Gateway for commissioning as officers in the Indian Army, Indian Navy, and Indian Air Force after 12th class, followed by 5-day SSB interview.",
    seatsOffered: "400+ per session",
    difficultyRating: 4.7,
  },
];
