export interface EntranceExam {
  id: string;
  name: string;
  shortName: string;
  stream: "Engineering" | "Medical" | "Commerce & Management" | "Law" | "Design & Arts" | "Defense & Civil";
  conductingBody: string;
  eligibility: string;
  annualApplicants: string;
  examMonth: string;
  examDateEstimate: string;
  applicationDeadline: string;
  status: "Registration Open" | "Upcoming" | "Announced" | "In Progress";
  officialUrl: string;
  keySubjects: string[];
  description: string;
  seatsOffered: string;
  difficultyRating: number; // 1 to 5
}

export const ENTRANCE_EXAMS: EntranceExam[] = [
  {
    id: "jee-main",
    name: "Joint Entrance Examination (Main)",
    shortName: "JEE Main",
    stream: "Engineering",
    conductingBody: "National Testing Agency (NTA)",
    eligibility: "Class 12 pass or appearing with Physics, Mathematics, and Chemistry/Tech subject",
    annualApplicants: "14+ Lakhs",
    examMonth: "January & April",
    examDateEstimate: "Session 1: Late Jan | Session 2: Early April",
    applicationDeadline: "Session 1: Nov-Dec | Session 2: Feb-Mar",
    status: "Announced",
    officialUrl: "https://jeemain.nta.nic.in",
    keySubjects: ["Physics", "Chemistry", "Mathematics"],
    description: "Gateway for admission to NITs, IIITs, CFTIs, and eligibility qualifier for JEE Advanced.",
    seatsOffered: "60,000+ across NITs/IIITs/GFTIs",
    difficultyRating: 4.5,
  },
  {
    id: "jee-advanced",
    name: "Joint Entrance Examination (Advanced)",
    shortName: "JEE Advanced",
    stream: "Engineering",
    conductingBody: "Rotational IIT (Zonal)",
    eligibility: "Top 2,50,000 qualifiers of JEE Main (Paper 1)",
    annualApplicants: "2.5 Lakhs (Capped)",
    examMonth: "May",
    examDateEstimate: "Last Sunday of May",
    applicationDeadline: "Early May",
    status: "Upcoming",
    officialUrl: "https://jeeadv.ac.in",
    keySubjects: ["Advanced Physics", "Advanced Chemistry", "Advanced Mathematics"],
    description: "The premier entrance exam for B.Tech/BS programs across the 23 prestigious Indian Institutes of Technology (IITs).",
    seatsOffered: "17,500+ IIT Seats",
    difficultyRating: 5.0,
  },
  {
    id: "bitsat",
    name: "BITS Admission Test",
    shortName: "BITSAT",
    stream: "Engineering",
    conductingBody: "BITS Pilani",
    eligibility: "75% aggregate in PCM in 12th board with at least 60% in each subject",
    annualApplicants: "3+ Lakhs",
    examMonth: "May & June",
    examDateEstimate: "Session 1: Late May | Session 2: Late June",
    applicationDeadline: "March - April",
    status: "Upcoming",
    officialUrl: "https://www.bitsadmission.com",
    keySubjects: ["Physics", "Chemistry", "Mathematics", "Logical Reasoning", "English"],
    description: "Computer-based online exam for admissions into BITS Pilani, Goa, and Hyderabad campuses.",
    seatsOffered: "3,000+ across 3 campuses",
    difficultyRating: 4.2,
  },
  {
    id: "neet-ug",
    name: "National Eligibility cum Entrance Test (UG)",
    shortName: "NEET UG",
    stream: "Medical",
    conductingBody: "National Testing Agency (NTA)",
    eligibility: "Class 12 with Physics, Chemistry, Biology/Biotech with minimum 50% marks (General)",
    annualApplicants: "24+ Lakhs",
    examMonth: "May",
    examDateEstimate: "First Sunday of May",
    applicationDeadline: "February - March",
    status: "Upcoming",
    officialUrl: "https://neet.nta.nic.in",
    keySubjects: ["Biology (Botany + Zoology)", "Physics", "Chemistry"],
    description: "Single unified entrance examination for MBBS, BDS, BAMS, BHMS, and veterinary seats across India (including AIIMS & JIPMER).",
    seatsOffered: "1,05,000+ MBBS Seats",
    difficultyRating: 4.8,
  },
  {
    id: "cuet-ug",
    name: "Common University Entrance Test (UG)",
    shortName: "CUET UG",
    stream: "Commerce & Management",
    conductingBody: "National Testing Agency (NTA)",
    eligibility: "Class 12 pass from any recognized board",
    annualApplicants: "19+ Lakhs",
    examMonth: "May - June",
    examDateEstimate: "Mid-May to Early June",
    applicationDeadline: "February - March",
    status: "Upcoming",
    officialUrl: "https://exams.nta.ac.in/CUET-UG",
    keySubjects: ["Domain Subjects", "General Aptitude Test", "English/Language"],
    description: "Unified national gateway for undergraduate admissions into Delhi University (SRCC, Stephen's, LSR), BHU, JNU, and 250+ central & state universities.",
    seatsOffered: "3,00,000+ across participating universities",
    difficultyRating: 3.8,
  },
  {
    id: "ipmat",
    name: "Integrated Program in Management Aptitude Test",
    shortName: "IPMAT",
    stream: "Commerce & Management",
    conductingBody: "IIM Indore / IIM Rohtak",
    eligibility: "Minimum 60% in 10th and 12th standard",
    annualApplicants: "35,000+",
    examMonth: "May",
    examDateEstimate: "Third Week of May",
    applicationDeadline: "March - April",
    status: "Upcoming",
    officialUrl: "https://www.iimidr.ac.in",
    keySubjects: ["Quantitative Ability (MCQ + Short Answer)", "Verbal Ability"],
    description: "Direct 5-year BBA+MBA entry into elite Indian Institutes of Management (IIM Indore, Rohtak, Ranchi, Bodh Gaya, Jammu).",
    seatsOffered: "600+ across IIMs",
    difficultyRating: 4.4,
  },
  {
    id: "clat",
    name: "Common Law Admission Test",
    shortName: "CLAT UG",
    stream: "Law",
    conductingBody: "Consortium of National Law Universities (NLUs)",
    eligibility: "Class 12 pass with minimum 45% (General/OBC)",
    annualApplicants: "65,000+",
    examMonth: "December",
    examDateEstimate: "First Sunday of December",
    applicationDeadline: "July - October",
    status: "Upcoming",
    officialUrl: "https://consortiumofnlus.ac.in",
    keySubjects: ["Legal Reasoning", "Current Affairs & GK", "Logical Reasoning", "English Language", "Quantitative Techniques"],
    description: "The primary entrance test for 5-year integrated BA/BBA LLB (Hons) across 24 premier National Law Universities (NLSIU Bengaluru, NALSAR, WBNUJS).",
    seatsOffered: "3,200+ NLU Seats",
    difficultyRating: 4.3,
  },
  {
    id: "uceed",
    name: "Undergraduate Common Entrance Examination for Design",
    shortName: "UCEED",
    stream: "Design & Arts",
    conductingBody: "IIT Bombay",
    eligibility: "Class 12 pass from any stream (Science/Commerce/Arts)",
    annualApplicants: "15,000+",
    examMonth: "January",
    examDateEstimate: "Third Sunday of January",
    applicationDeadline: "September - November",
    status: "Announced",
    officialUrl: "https://www.uceed.iitb.ac.in",
    keySubjects: ["Visualization & Spatial Ability", "Observation & Design Sensitivity", "Analytical Reasoning", "Drawing Test"],
    description: "Entrance for Bachelor of Design (B.Des) at IIT Bombay, IIT Delhi, IIT Guwahati, IIT Hyderabad, and IIITDM Jabalpur.",
    seatsOffered: "220+ IIT B.Des seats",
    difficultyRating: 4.4,
  },
  {
    id: "nid-dat",
    name: "National Institute of Design - Design Aptitude Test",
    shortName: "NID DAT",
    stream: "Design & Arts",
    conductingBody: "National Institute of Design",
    eligibility: "Class 12 pass from any recognized board",
    annualApplicants: "20,000+",
    examMonth: "December / January",
    examDateEstimate: "Prelims: Late Dec | Mains: April",
    applicationDeadline: "September - December",
    status: "Announced",
    officialUrl: "https://admissions.nid.edu",
    keySubjects: ["Design Aptitude", "General Knowledge & Observation", "Studio Test & Personal Interview"],
    description: "India's most prestigious design school entrance for B.Des across NID Ahmedabad, Gandhinagar, Bengaluru, Kurukshetra, and Vijayawada.",
    seatsOffered: "425 B.Des seats",
    difficultyRating: 4.6,
  },
  {
    id: "nda-na",
    name: "National Defence Academy & Naval Academy Examination",
    shortName: "NDA / NA",
    stream: "Defense & Civil",
    conductingBody: "Union Public Service Commission (UPSC)",
    eligibility: "Unmarried male & female candidates, 12th pass (Physics & Math for Air Force/Navy)",
    annualApplicants: "6+ Lakhs",
    examMonth: "April (NDA I) & September (NDA II)",
    examDateEstimate: "NDA I: Mid April | NDA II: Early Sept",
    applicationDeadline: "Jan (NDA I) | June (NDA II)",
    status: "Upcoming",
    officialUrl: "https://upsc.gov.in",
    keySubjects: ["Mathematics (300 Marks)", "General Ability Test (600 Marks)"],
    description: "Gateway for commissioning as officers in the Indian Army, Indian Navy, and Indian Air Force after 12th class, followed by 5-day SSB interview.",
    seatsOffered: "400+ per session",
    difficultyRating: 4.7,
  },
  {
    id: "iat-iiser",
    name: "IISER Aptitude Test",
    shortName: "IAT",
    stream: "Medical",
    conductingBody: "Indian Institutes of Science Education and Research (IISER)",
    eligibility: "Class 12 with at least 3 subjects out of PCMB",
    annualApplicants: "1.2 Lakhs",
    examMonth: "June",
    examDateEstimate: "Second Sunday of June",
    applicationDeadline: "March - May",
    status: "Upcoming",
    officialUrl: "https://iiseradmission.in",
    keySubjects: ["Physics", "Chemistry", "Mathematics", "Biology"],
    description: "Premier entrance exam for 5-year BS-MS dual degree research programs at IISERs (Pune, Kolkata, Mohali, Bhopal, Thiruvananthapuram, Tirupati, Berhampur) and IISc Bangalore.",
    seatsOffered: "1,900+ Research Seats",
    difficultyRating: 4.6,
  },
  {
    id: "nata",
    name: "National Aptitude Test in Architecture",
    shortName: "NATA",
    stream: "Design & Arts",
    conductingBody: "Council of Architecture (CoA)",
    eligibility: "12th with Physics, Chemistry & Mathematics or 10+3 Diploma with Mathematics",
    annualApplicants: "50,000+",
    examMonth: "April - July (Multiple Attempts)",
    examDateEstimate: "Every weekend from April to July",
    applicationDeadline: "Rolling registration through June",
    status: "Registration Open",
    officialUrl: "https://www.nata.in",
    keySubjects: ["Drawing & Composition", "Visual Perception & Architectural Awareness", "Mathematics"],
    description: "National benchmark test required for admission to 5-year B.Arch programs across all recognized architecture colleges in India.",
    seatsOffered: "25,000+ B.Arch seats",
    difficultyRating: 3.7,
  },
];
